import { Language } from "@/types";

export const TRANSLATION_LANGUAGES: Language[] = [
  { name: "Arabic", alpha2: "ar", countryCode: "AE" },
  { name: "Bengali", alpha2: "bn", countryCode: "BD" },
  { name: "Bulgarian", alpha2: "bg", countryCode: "BG" },
  { name: "Catalan", alpha2: "ca", countryCode: "ES" },
  { name: "Croatian", alpha2: "hr", countryCode: "HR" },
  { name: "Czech", alpha2: "cs", countryCode: "CZ" },
  { name: "Danish", alpha2: "da", countryCode: "DK" },
  { name: "Dutch", alpha2: "nl", countryCode: "NL" },
  { name: "English", alpha2: "en", countryCode: "US" },
  { name: "Estonian", alpha2: "et", countryCode: "EE" },
  { name: "Finnish", alpha2: "fi", countryCode: "FI" },
  { name: "French", alpha2: "fr", countryCode: "FR" },
  { name: "German", alpha2: "de", countryCode: "DE" },
  { name: "Greek", alpha2: "el", countryCode: "GR" },
  { name: "Hindi", alpha2: "hi", countryCode: "IN" },
  { name: "Hungarian", alpha2: "hu", countryCode: "HU" },
  { name: "Indonesian", alpha2: "id", countryCode: "ID" },
  { name: "Italian", alpha2: "it", countryCode: "IT" },
  { name: "Japanese", alpha2: "ja", countryCode: "JP" },
  { name: "Korean", alpha2: "ko", countryCode: "KR" },
  { name: "Latvian", alpha2: "lv", countryCode: "LV" },
  { name: "Lithuanian", alpha2: "lt", countryCode: "LT" },
  { name: "Malay", alpha2: "ms", countryCode: "MY" },
  { name: "Marathi", alpha2: "mr", countryCode: "IN" },
  { name: "Mongolian", alpha2: "mn", countryCode: "MN" },
  { name: "Norwegian", alpha2: "no", countryCode: "NO" },
  { name: "Persian", alpha2: "fa", countryCode: "IR" },
  { name: "Polish", alpha2: "pl", countryCode: "PL" },
  { name: "Portuguese", alpha2: "pt", countryCode: "PT" },
  { name: "Romanian", alpha2: "ro", countryCode: "RO" },
  { name: "Russian", alpha2: "ru", countryCode: "" },
  { name: "Slovak", alpha2: "sk", countryCode: "SK" },
  { name: "Slovenian", alpha2: "sl", countryCode: "SI" },
  { name: "Spanish", alpha2: "es", countryCode: "ES" },
  { name: "Swahili", alpha2: "sw", countryCode: "TZ" },
  { name: "Swedish", alpha2: "sv", countryCode: "SE" },
  { name: "Tamil", alpha2: "ta", countryCode: "IN" },
  { name: "Thai", alpha2: "th", countryCode: "TH" },
  { name: "Turkish", alpha2: "tr", countryCode: "TR" },
  { name: "Ukrainian", alpha2: "uk", countryCode: "UA" },
  { name: "Urdu", alpha2: "ur", countryCode: "PK" },
  { name: "Vietnamese", alpha2: "vi", countryCode: "VN" }
] as const;
